### ISSUE TITLE
Error when building navmesh

### ISSUE THREAD

**Issue by frnsys** [vincent/recast.js#21]
I'm trying to generate a navmesh but am encountering the following error:

```
recast.js:181367Uncaught abort() at Error
    at jsStackTrace (http://localhost:8081/bundle.js:44725:14)
    at stackTrace (http://localhost:8081/bundle.js:44742:23)
    at Object.abort (http://localhost:8081/bundle.js:224122:45)
    at _abort (http://localhost:8081/bundle.js:51801:23)
    at _free (http://localhost:8081/bundle.js:104765:22)
    at __ZdlPv [operator delete(void*)] (http://localhost:8081/bundle.js:223212:3)
    at __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev [std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()] (http://localhost:8081/bundle.js:217345:30)
    at Array.__ZN10emscripten8internal7InvokerIbJNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEE6invokeEPFbS8_EPNS0_11BindingTypeIS8_EUt_E [emscripten::internal::Invoker<bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::invoke(bool (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >), emscripten::internal::BindingType<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::'unnamed'*)] (http://localhost:8081/bundle.js:201544:3)
    at dynCall_iii (http://localhost:8081/bundle.js:219099:40)
    at dynCall_iii_36 (eval at makeDynCaller (http://localhost:8081/bundle.js:50427:20), <anonymous>:4:12)
```

The code: 

```
var exporter = new THREE.OBJExporter();
var geometry = new THREE.BoxGeometry(1,1,1),
    material = new THREE.MeshLambertMaterial(),
    mesh = new THREE.Mesh(geometry, material);
var objData = exporter.parse(mesh);
recast.OBJDataLoader(objData, function() {
  recast.buildSolo(); // have also tried buildTiled()
});
```

I haven't used emscripten before so I'm unsure what to make of the error. This is on Ubuntu 14.04 and occurred with both Chrome 54.0.2840.71 and Firefox 49.0.2.

**Comment by vincent** [comment]
Sorry I let this sink in. From your code it seems it simply cannot generate a navmesh from a simple tiny cude, which is not so surprising.
