### ISSUE TITLE
nodejs environment issue 

### ISSUE THREAD

**Issue by jdestefx** [vincent/recast.js#23]
Installed recastjs via "npm install". When I try to load an obj file, it throws an error.

[root@localhost node]# node  test.js
warning: a problem occurred in builtin C++ name demangling; build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling

/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:988
      throw ex;
      ^
abort() at Error
    at jsStackTrace (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:1883:13)
    at stackTrace (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:1900:22)
    at Object.abort (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:176169:25)
    at _abort (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:8438:22)
    at _free (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:50996:21)
    at __ZdlPv [operator delete()] (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:172463:2)
    at __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev [??_()] (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:162714:2)
    at __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev [??_()] (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:163865:2)
    at Array.__ZN10emscripten8internal7InvokerIbJNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEE6invokeEPFbS8_EPNS0_11BindingTypeIS8_EUt_E [? emscripten::internal::Invoker<bool, undefined?J?>?_()] (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:147338:2)
    at dynCall_iii (/projects.git/phpmmo/node/node_modules/recastjs/lib/recast.js:170382:39)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

code:

var recast = require('recastjs');

recast.OBJLoader('felwitheb.obj', function() {

});

**Comment by jdestefx** [comment]
This appears to be some sort of problem with the OBJ file itself.  The dungeon.obj file loads fine.

**Comment by jdestefx** [comment]
closing.
